on: push
name: Build and deploy staging branch
jobs:
  buildAndDeploy:
    name: Build and deploy staging branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: composer install
      uses: MilesChou/composer-action@master
      with:
        args: install --working-dir src
    - name: rsync
      uses: contention/rsync-deployments@master
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        RVM_MACHINE: ${{ secrets.RVM_MACHINE }}
        RVM_USERNAME: ${{ secrets.RVM_USERNAME }}
      with:
        args: -rv --exclude /dev/ --exclude .gitignore $RVM_USERNAME@$RVM_MACHINE:/var/www/api
