on: push
name: Build and deploy
jobs:
  filtersForGitHubActions-Branch:
    name: Filters for GitHub Actions - branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: MilesChou/composer-action@master
      uses: MilesChou/composer-action@master
      with:
        args: install
    - name: contention/rsync-deployments@master
      uses: contention/rsync-deployments@master
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        RVM_MACHINE: ${{ secrets.RVM_MACHINE }}
        RVM_USERNAME: ${{ secrets.RVM_USERNAME }}
      with:
        args: '"-rv", "--exclude /dev/ --exclude .gitignore", "$RVM_USERNAME@$RVM_MACHINE:/var/www/api"'
