on: 
  push:
    branches:
      - stage
name: Build and deploy staging branch
jobs:
  buildAndDeploy:
    name: Build and deploy staging branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: composer install
      uses: MilesChou/composer-action@master
      with:
        args: install --working-dir src
    - name: Deploy the solution
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        RVM_MACHINE: ${{ secrets.RVM_MACHINE }}
        RVM_USERNAME: ${{ secrets.RVM_USERNAME }}
      run: |
        DEPLOY_FOLDER="$GITHUB_WORKSPACE/src/"
        SSH_PATH="$HOME/.ssh"
        mkdir "$SSH_PATH"
        echo "$DEPLOY_KEY" > "$SSH_PATH/deploy_key"
        chmod 600 "$SSH_PATH/deploy_key"
        sh -c "rsync -rvz --omit-dir-times -e 'ssh -i $SSH_PATH/deploy_key -o StrictHostKeyChecking=no' $DEPLOY_FOLDER $RVM_USERNAME@$RVM_MACHINE:/var/www/api/"
        sh -c "ssh -i $SSH_PATH/deploy_key $RVM_USERNAME@$RVM_MACHINE 'cp ~/.env /var/www/api/'"